version: '3'
services:
  postgres:
    image: postgres:13
    container_name: auth-backend-course-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5434}:5432
  postgres-test:
    image: postgres:13
    container_name: auth-backend-course-testdb
    env_file:
      - .env.test
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5433}:5432